version: '3'
services:
  rabbitmq:
    image: rabbitmq
    ports:
      - 15672:15672
      - 5672:5672
  elasticsearch:
    image: elasticsearch:5
    ports:
      - 9200:9200
      - 9300:9300
  ipfs:
    image: ipfs/go-ipfs
    ports:
      - 4001:4001
      - 5001:5001
      - 8080:8080
  ipfs-tika:
    image: ipfssearch/ipfs-tika
    ports:
      - 8081:8081
    depends_on:
      - ipfs
    environment:
      - IPFS_GATEWAY=http://ipfs:8080/
  ipfs-search:
    build: .
    depends_on:
      - rabbitmq
      - elasticsearch
      - ipfs
      - ipfs-tika
    environment:
      - IPFS_TIKA_URL=http://ipfs-tika:8081
      - IPFS_API_URL=ipfs:5001
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - AMQP_URL=amqp://guest:guest@rabbitmq:5672/
